### PR TITLE
Make choice fields compatible with >=SF 2.7

### LINKED ISSUE #434: Admin order element - update sets 'Product type' to null (0)
#### Sonata packages

```bash
sonata-project/admin-bundle              3.16.0             The missing Symfony Admin Generator
sonata-project/block-bundle              3.3.2              Symfony SonataBlockBundle
sonata-project/cache                     1.0.7              Cache library
sonata-project/cache-bundle              2.3.1              This bundle provides caching services
sonata-project/classification-bundle     3.3.0              Symfony SonataClassificationBundle
sonata-project/comment-bundle            3.0.0              Integrate the FOSCommentBundle in the Sonata Project
sonata-project/core-bundle               3.3.0              Symfony SonataCoreBundle
sonata-project/datagrid-bundle           2.2.1              Symfony SonataDatagridBundle
sonata-project/doctrine-extensions       1.0.2              Doctrine2 behavioral extensions
sonata-project/doctrine-orm-admin-bundle 3.1.4              Symfony Sonata / Integrate Doctrine ORM into the SonataAdminBundle
sonata-project/easy-extends-bundle       2.1.10             Symfony SonataEasyExtendsBundle
sonata-project/ecommerce                 dev-master 674a359 E-Commerce solution provided by Sonata
sonata-project/exporter                  1.7.1              Lightweight Exporter library
sonata-project/formatter-bundle          3.2.1              Symfony SonataFormatterBundle
sonata-project/google-authenticator      1.0.2              Library to integrate Google Authenticator into a PHP project
sonata-project/intl-bundle               2.3.0              Symfony SonataIntlBundle
sonata-project/media-bundle              3.5.1              Symfony SonataMediaBundle
sonata-project/news-bundle               3.1.2              Symfony SonataNewsBundle
sonata-project/notification-bundle       3.1.0              Symfony SonataNotificationBundle
sonata-project/page-bundle               3.4.1              This bundle provides a Site and Page management through container and block services
sonata-project/seo-bundle                2.1.0              Symfony SonataSeoBundle
sonata-project/sonata-composer           dev-master 6ebe1f3 
sonata-project/timeline-bundle           3.1.0              Integrates SpyTimelineBundle into Sonata
sonata-project/user-bundle               3.2.3              Symfony SonataUserBundle
```

#### Symfony packages

```bash
symfony/assetic-bundle     v2.8.1  Integrates Assetic into Symfony2
symfony/monolog-bundle     v2.12.1 Symfony MonologBundle
symfony/phpunit-bridge     v2.8.19 Symfony PHPUnit Bridge
symfony/polyfill-apcu      v1.3.0  Symfony polyfill backporting apcu_* functions to lower PHP versions
symfony/polyfill-intl-icu  v1.3.0  Symfony polyfill for intl's ICU-related data and classes
symfony/polyfill-mbstring  v1.3.0  Symfony polyfill for the Mbstring extension
symfony/polyfill-php54     v1.3.0  Symfony polyfill backporting some PHP 5.4+ features to lower PHP versions
symfony/polyfill-php55     v1.3.0  Symfony polyfill backporting some PHP 5.5+ features to lower PHP versions
symfony/polyfill-php56     v1.3.0  Symfony polyfill backporting some PHP 5.6+ features to lower PHP versions
symfony/polyfill-php70     v1.3.0  Symfony polyfill backporting some PHP 7.0+ features to lower PHP versions
symfony/polyfill-util      v1.3.0  Symfony utilities for portability of PHP codes
symfony/security-acl       v3.0.0  Symfony Security Component - ACL (Access Control List)
symfony/swiftmailer-bundle v2.5.4  Symfony SwiftmailerBundle
symfony/symfony            v2.8.19 The Symfony PHP framework
```

#### PHP version

```bash
PHP 7.0.17 (cli) (built: Mar 16 2017 08:19:49) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.0.17, Copyright (c) 1999-2017, by Zend Technologies
    with Xdebug v2.5.1, Copyright (c) 2002-2017, by Derick Rethans
```

## Subject

Admin order element - update sets 'Product type' to null (0)

## Steps to reproduce
Once and order has been made, go to Order List
Click reference
Click Elements
Click ID
Make a change (such as delivery)
Click Update

## Expected results
Order element is updated

## Actual results
Order is updated successfully however, 'Product type' is set to null (0) on Order Element list

## Stack trace

`[1] Symfony\Component\Debug\Exception\ContextErrorException: Notice: Undefined variable: gh
    at n/a
        in /var/www/html/sonata3/vendor/sonata-project/ecommerce/src/OrderBundle/Entity/BaseOrderElement.php line 418

    at Symfony\Component\Debug\ErrorHandler->handleError('8', 'Undefined variable: gh', '/var/www/html/sonata3/vendor/sonata-project/ecommerce/src/OrderBundle/Entity/BaseOrderElement.php', '418', array('productType' => '0'))
        in /var/www/html/sonata3/vendor/sonata-project/ecommerce/src/OrderBundle/Entity/BaseOrderElement.php line 418

    at Sonata\OrderBundle\Entity\BaseOrderElement->setProductType('0')
        in /var/www/html/sonata3/vendor/symfony/symfony/src/Symfony/Component/PropertyAccess/PropertyAccessor.php line 605

    at Symfony\Component\PropertyAccess\PropertyAccessor->writeProperty(array(object(OrderElement), object(OrderElement)), 'productType', '0')
        in /var/www/html/sonata3/vendor/symfony/symfony/src/Symfony/Component/PropertyAccess/PropertyAccessor.php line 201

    at Symfony\Component\PropertyAccess\PropertyAccessor->setValue(object(OrderElement), object(PropertyPath), '0')
        in /var/www/html/sonata3/vendor/symfony/symfony/src/Symfony/Component/Form/Extension/Core/DataMapper/PropertyPathMapper.php line 93

    at Symfony\Component\Form\Extension\Core\DataMapper\PropertyPathMapper->mapFormsToData(object(RecursiveIteratorIterator), object(OrderElement))
        in /var/www/html/sonata3/vendor/symfony/symfony/src/Symfony/Component/Form/Form.php line 635

    at Symfony\Component\Form\Form->submit(array(), true)
        in /var/www/html/sonata3/vendor/symfony/symfony/src/Symfony/Component/Form/Extension/HttpFoundation/HttpFoundationRequestHandler.php line 113

    at Symfony\Component\Form\Extension\HttpFoundation\HttpFoundationRequestHandler->handleRequest(object(Form), object(SiteRequest))
        in /var/www/html/sonata3/vendor/symfony/symfony/src/Symfony/Component/Form/Form.php line 501

    at Symfony\Component\Form\Form->handleRequest(object(SiteRequest))
        in /var/www/html/sonata3/vendor/sonata-project/admin-bundle/Controller/CRUDController.php line 257

    at Sonata\AdminBundle\Controller\CRUDController->editAction('2')
        in  line 

    at call_user_func_array(array(object(CRUDController), 'editAction'), array('2'))
        in /var/www/html/sonata3/app/bootstrap.php.cache line 3247

    at Symfony\Component\HttpKernel\HttpKernel->handleRaw(object(SiteRequest), '1')
        in /var/www/html/sonata3/app/bootstrap.php.cache line 3206

    at Symfony\Component\HttpKernel\HttpKernel->handle(object(SiteRequest), '1', true)
        in /var/www/html/sonata3/app/bootstrap.php.cache line 3360

    at Symfony\Component\HttpKernel\DependencyInjection\ContainerAwareHttpKernel->handle(object(SiteRequest), '1', true)
        in /var/www/html/sonata3/app/bootstrap.php.cache line 2562

    at Symfony\Component\HttpKernel\Kernel->handle(object(SiteRequest))
        in /var/www/html/sonata3/web/app_dev.php line 21`

### PR DESCRIPTION
**Pull request by ZRazor**
I am targeting this branch, because it is a bug fix.

Closes #434

## Changelog

```markdown
### Fixed
- Made `choice` fields compatible with >=SF 2.7
```

### CODE REVIEW

File: src/BasketBundle/Form/AddressType.php [hunk 1]
```diff
@@ -97,10 +97,21 @@ public function buildForm(FormBuilderInterface $builder, array $options)
         $builder->add('name', null, array('required' => !count($addresses)));
 
         if (isset($options['types'])) {
-            $builder->add('type', $choiceType, array(
-                'choices' => $options['types'],
-                'translation_domain' => 'SonataCustomerBundle', )
+            $types = $options['types'];
+            $typesOptions = array(
```
Comment (greg0ire) [inline src/BasketBundle/Form/AddressType.php]: `typeOptions` should look better

File: src/BasketBundle/Form/AddressType.php [hunk 2]
```diff
@@ -97,10 +97,21 @@ public function buildForm(FormBuilderInterface $builder, array $options)
...
+                'translation_domain' => 'SonataCustomerBundle',
             );
+            // NEXT_MAJOR: Remove this "if" (when requirement of Symfony is >= 2.7)
+            if (method_exists('Symfony\Component\Form\AbstractType', 'configureOptions')) {
+                $types = array_flip($types);
+                // choice_as_value options is not needed in SF 3.0+
```
Comment (greg0ire) [inline src/BasketBundle/Form/AddressType.php]: "option"

File: src/Component/Form/Type/VariationChoiceType.php [hunk 3]
```diff
@@ -49,13 +49,23 @@ public function buildForm(FormBuilderInterface $builder, array $options)
...
+                $choiceValues = array_flip($choiceValues);
+                // choice_as_value option is not needed in SF 3.0+
+                if (method_exists('Symfony\Component\Form\FormTypeInterface', 'setDefaultOptions')) {
+                    $choiceOptions['choices_as_values'] = true;
+                }
+            }
+            $choiceOptions['choices'] = $choiceValues;
+
             $builder->add($choiceTitle, $choiceType, array_merge(
-                    array('translation_domain' => 'SonataProductBundle'),
```
Comment (jordisala1991) [inline src/Component/Form/Type/VariationChoiceType.php]: This should remain as is, because otherwise you won't be able to override this `translation_domain` with your custom options. Am I wrong?

Not sure if you can use $options['field_options'] to pass a custom `translation_domain`.

It is only on this choice type tho, because the other didn't even had the option before.

Comment (ZRazor) [inline src/Component/Form/Type/VariationChoiceType.php]: I'll move `$choiceOptions` before `$options['field_options']` in `array_merge` then it should be okay.

**Comment by jordisala1991** [comment]
Can you review again @greg0ire ?

**Comment by jordisala1991** [comment]
Thank you @ZRazor

**Comment by pixel-paul** [comment]
Thanks @ZRazor and all.
