### PR TITLE
fix block deprecated method

### LINKED ISSUE #386: Can't view a single product
#### Sonata packages

```bash
$ composer show sonata-project/*
sonata-project/admin-bundle              3.4.0  The missing Symfony Admin Generator
sonata-project/block-bundle              3.1.1  Symfony SonataBlockBundle
sonata-project/cache                     1.0.7  Cache library
sonata-project/classification-bundle     3.1.0  Symfony SonataClassificationBundle
sonata-project/comment-bundle            3.0.0  Integrate the FOSCommentBundle in the Sonata Project
sonata-project/core-bundle               3.0.3  Symfony SonataCoreBundle
sonata-project/datagrid-bundle           2.2    Symfony SonataDatagridBundle
sonata-project/doctrine-extensions       1.0.2  Doctrine2 behavioral extensions
sonata-project/doctrine-orm-admin-bundle 3.0.5  Symfony Sonata / Integrate Doctrine ORM into the SonataAdminBundle
sonata-project/easy-extends-bundle       2.1.10 Symfony SonataEasyExtendsBundle
sonata-project/ecommerce                 2.0.0  E-Commerce solution provided by Sonata
sonata-project/exporter                  1.6.0  Lightweight Exporter library
sonata-project/formatter-bundle          3.0.1  Symfony SonataFormatterBundle
sonata-project/google-authenticator      1.0.2  Library to integrate Google Authenticator into a PHP project
sonata-project/intl-bundle               2.2.4  Symfony SonataIntlBundle
sonata-project/media-bundle              3.1.0  Symfony SonataMediaBundle
sonata-project/notification-bundle       3.0.0  Symfony SonataNotificationBundle
sonata-project/seo-bundle                2.0.2  Symfony SonataSeoBundle
sonata-project/user-bundle               3.0.1  Symfony SonataUserBundle
```
#### Symfony packages

```bash
$ composer show symfony/*
symfony/assetic-bundle     v2.8.0  Integrates Assetic into Symfony2
symfony/monolog-bundle     2.11.1  Symfony MonologBundle
symfony/phpunit-bridge     v2.8.9  Symfony PHPUnit Bridge
symfony/polyfill-apcu      v1.2.0  Symfony polyfill backporting apcu_* functions to lower PHP versions
symfony/polyfill-intl-icu  v1.2.0  Symfony polyfill for intl's ICU-related data and classes
symfony/polyfill-mbstring  v1.2.0  Symfony polyfill for the Mbstring extension
symfony/polyfill-php54     v1.2.0  Symfony polyfill backporting some PHP 5.4+ features to lower PHP versions
symfony/polyfill-php55     v1.2.0  Symfony polyfill backporting some PHP 5.5+ features to lower PHP versions
symfony/polyfill-php56     v1.2.0  Symfony polyfill backporting some PHP 5.6+ features to lower PHP versions
symfony/polyfill-php70     v1.2.0  Symfony polyfill backporting some PHP 7.0+ features to lower PHP versions
symfony/polyfill-util      v1.2.0  Symfony utilities for portability of PHP codes
symfony/security-acl       v3.0.0  Symfony Security Component - ACL (Access Control List)
symfony/swiftmailer-bundle v2.3.11 Symfony SwiftmailerBundle
symfony/symfony            v2.8.9  The Symfony PHP framework
```

#### PHP version

```bash
$ php -v
PHP 5.6.23-1+deprecated+dontuse+deb.sury.org~trusty+1 (cli) 
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2016, by Zend Technologies
    with blackfire v1.11.1, https://blackfire.io, by Blackfireio Inc.

```

## Subject

I can't view a single product

## Steps to reproduce

Create a Product with SonataAdmin then try to access it with this URI (/shop/product/{slug}/{id})

## Expected results

The view of product

## Actual results

> An exception has been thrown during the rendering of a template ("The options "form_field_options", "product", "variations_properties" do not exist. Defined options are: "attr", "extra_cache_keys", "template", "ttl", "use_cache".") in SonataProductBundle:Product:view.html.twig at line 110.

### PR DESCRIPTION
**Pull request by rande**
I am targetting this branch, because there it is the latest one :)

Fixes #386 

## Changelog

```markdown
### Changed
 - use `configureSettings ` instead of `setDefaultSettings`

### Fixed
 - fix missing configuration to the CoreBundle's FormHelper
```

## Subject

There is a regression with the method called by BlockContextManager. Only ``configureSettings`` methods are being called.

### CODE REVIEW

**Comment by OskarStark** [comment]
LGTM 👌🏻

**Comment by OskarStark** [comment]
@Soullivaneuh stuck build

File: src/BasketBundle/Block/BasketBlockService.php [hunk 1]
```diff
@@ -59,7 +59,7 @@ public function getName()
     /**
      * {@inheritdoc}
      */
-    public function setDefaultSettings(OptionsResolverInterface $resolver)
+    public function configureSettings(OptionsResolver $resolver)
```
Comment (OskarStark) [inline src/BasketBundle/Block/BasketBlockService.php]: this is a BC break, isnÄt it?

Comment (rande) [inline src/BasketBundle/Block/BasketBlockService.php]: no as the current code does not work...

**Comment by rande** [comment]
Can we merge this PR ?

**Comment by greg0ire** [comment]
No b/c the build is stuck. Let's ask @Soullivaneuh

**Comment by greg0ire** [comment]
Thanks @rande

**Comment by Nehadigi** [comment]
HI,

I am using e-commerce version 2.1.1 but my basket page and single product page is empty.
