### PR TITLE
Master - make order steps working on front office for symfony 4.1 - PR 2

### LINKED ISSUE #601: Master - Sf 4.3 - add product to cart -  Call to a member function getManager() on null
On sf 4.3, Ecommerce branch Master

unable to add product to the basket, i got error `Call to a member function getManager() on null` when trying to add element in the basket.

#### Sonata packages
```
composer show --latest 'sonata-project/*'

sonata-project/admin-bundle              3.54.0             = 3.54.0
sonata-project/block-bundle              3.18.1             = 3.18.1
sonata-project/cache                     2.0.1              = 2.0.1
sonata-project/classification-bundle     3.9.0              = 3.9.0
sonata-project/comment-bundle            3.1.1              = 3.1.1
sonata-project/core-bundle               3.17.0             = 3.17.0
sonata-project/datagrid-bundle           2.5.0              ~ 3.0.0
sonata-project/doctrine-extensions       1.3.1              = 1.3.1
sonata-project/doctrine-orm-admin-bundle 3.10.0             = 3.10.0
sonata-project/easy-extends-bundle       2.5.0              = 2.5.0
sonata-project/ecommerce                 dev-master 46711cf = dev-master 46711cf
sonata-project/exporter                  2.0.1              = 2.0.1
sonata-project/formatter-bundle          4.1.3              = 4.1.3
sonata-project/intl-bundle               2.7.0              = 2.7.0
sonata-project/media-bundle              3.20.1             = 3.20.1
sonata-project/media-orm-pack            1.0.0              = 1.0.0
sonata-project/notification-bundle       3.6.2              = 3.6.2
sonata-project/seo-bundle                2.7.0              = 2.7.0
sonata-project/timeline-bundle           3.4.0              = 3.4.0
sonata-project/user-bundle               4.5.0              = 4.5.0

```

#### Symfony packages

```
$ composer show --latest 'symfony/*'
Restricting packages listed in "symfony/symfony" to "4.3.*"
symfony/apache-pack                v1.0.1  = v1.0.1  A pack for Apache supp...
symfony/asset                      v4.3.4  = v4.3.4  Symfony Asset Component
symfony/browser-kit                v4.3.4  = v4.3.4  Symfony BrowserKit Com...
symfony/cache                      v4.3.4  = v4.3.4  Symfony Cache componen...
symfony/cache-contracts            v1.1.5  = v1.1.5  Generic abstractions r...
symfony/config                     v4.3.4  = v4.3.4  Symfony Config Component
symfony/console                    v4.3.4  = v4.3.4  Symfony Console Component
symfony/css-selector               v4.3.4  = v4.3.4  Symfony CssSelector Co...
symfony/debug                      v4.3.4  = v4.3.4  Symfony Debug Component
symfony/dependency-injection       v4.3.4  = v4.3.4  Symfony DependencyInje...
symfony/doctrine-bridge            v4.3.4  = v4.3.4  Symfony Doctrine Bridge
symfony/dom-crawler                v4.3.4  = v4.3.4  Symfony DomCrawler Com...
symfony/dotenv                     v4.3.4  = v4.3.4  Registers environment ...
symfony/event-dispatcher           v4.3.4  = v4.3.4  Symfony EventDispatche...
symfony/event-dispatcher-contracts v1.1.5  = v1.1.5  Generic abstractions r...
symfony/expression-language        v4.3.4  = v4.3.4  Symfony ExpressionLang...
symfony/filesystem                 v4.3.4  = v4.3.4  Symfony Filesystem Com...
symfony/finder                     v4.3.4  = v4.3.4  Symfony Finder Component
symfony/flex                       v1.4.6  = v1.4.6  Composer plugin for Sy...
symfony/form                       v4.3.4  = v4.3.4  Symfony Form Component
symfony/framework-bundle           v4.3.4  = v4.3.4  Symfony FrameworkBundle
symfony/http-foundation            v4.3.4  = v4.3.4  Symfony HttpFoundation...
symfony/http-kernel                v4.3.4  = v4.3.4  Symfony HttpKernel Com...
symfony/inflector                  v4.3.4  = v4.3.4  Symfony Inflector Comp...
symfony/intl                       v4.3.4  = v4.3.4  A PHP replacement laye...
symfony/maker-bundle               v1.13.0 = v1.13.0 Symfony Maker helps yo...
symfony/mime                       v4.3.4  = v4.3.4  A library to manipulat...
symfony/monolog-bridge             v4.3.4  = v4.3.4  Symfony Monolog Bridge
symfony/monolog-bundle             v3.4.0  = v3.4.0  Symfony MonologBundle
symfony/options-resolver           v4.3.4  = v4.3.4  Symfony OptionsResolve...
symfony/phpunit-bridge             v4.3.4  = v4.3.4  Symfony PHPUnit Bridge
symfony/polyfill-intl-icu          v1.12.0 = v1.12.0 Symfony polyfill for i...
symfony/polyfill-intl-idn          v1.12.0 = v1.12.0 Symfony polyfill for i...
symfony/polyfill-mbstring          v1.12.0 = v1.12.0 Symfony polyfill for t...
symfony/polyfill-php72             v1.12.0 = v1.12.0 Symfony polyfill backp...
symfony/polyfill-php73             v1.12.0 = v1.12.0 Symfony polyfill backp...
symfony/process                    v4.3.4  = v4.3.4  Symfony Process Component
symfony/profiler-pack              v1.0.4  = v1.0.4  A pack for the Symfony...
symfony/property-access            v4.3.4  = v4.3.4  Symfony PropertyAccess...
symfony/property-info              v4.3.4  = v4.3.4  Symfony Property Info ...
symfony/routing                    v4.3.4  = v4.3.4  Symfony Routing Component
symfony/security-acl               v3.0.2  = v3.0.2  Symfony Security Compo...
symfony/security-bundle            v4.3.4  = v4.3.4  Symfony SecurityBundle
symfony/security-core              v4.3.4  = v4.3.4  Symfony Security Compo...
symfony/security-csrf              v4.3.4  = v4.3.4  Symfony Security Compo...
symfony/security-guard             v4.3.4  = v4.3.4  Symfony Security Compo...
symfony/security-http              v4.3.4  = v4.3.4  Symfony Security Compo...
symfony/service-contracts          v1.1.6  = v1.1.6  Generic abstractions r...
symfony/stopwatch                  v4.3.4  = v4.3.4  Symfony Stopwatch Comp...
symfony/swiftmailer-bundle         v3.2.8  = v3.2.8  Symfony SwiftmailerBundle
symfony/templating                 v4.3.4  = v4.3.4  Symfony Templating Com...
symfony/test-pack                  v1.0.6  = v1.0.6  A pack for functional ...
symfony/translation                v4.3.4  = v4.3.4  Symfony Translation Co...
symfony/translation-contracts      v1.1.6  = v1.1.6  Generic abstractions r...
symfony/twig-bridge                v4.3.4  = v4.3.4  Symfony Twig Bridge
symfony/twig-bundle                v4.3.4  = v4.3.4  Symfony TwigBundle
symfony/validator                  v4.3.4  = v4.3.4  Symfony Validator Comp...
symfony/var-dumper                 v4.3.4  = v4.3.4  Symfony mechanism for ...
symfony/var-exporter               v4.3.4  = v4.3.4  A blend of var_export(...
symfony/web-profiler-bundle        v4.3.4  = v4.3.4  Symfony WebProfilerBundle
symfony/web-server-bundle          v4.3.4  = v4.3.4  Symfony WebServerBundle
symfony/yaml                       v4.3.4  = v4.3.4  Symfony Yaml Component

```

#### PHP version

```
$  php -v
PHP 7.2.18 (cli) (built: Apr 30 2019 23:32:39) ( ZTS MSVC15 (Visual C++ 2017) x64 )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies

```

## Actual results

```
Sonata\Component\Basket\BasketElement.php into method setProductId

error occured in this line

product = $this->getProductDefinition()->getManager()->findOneBy(['id' => $productId]);

=> $this->getProductDefinition is null 

```

```
Error:
Call to a member function getManager() on null

  at vendor/sonata-project/ecommerce/src/Component/Basket/BasketElement.php:133
  at Sonata\Component\Basket\BasketElement->setProductId('1')
     (vendor/symfony/property-access/PropertyAccessor.php:551)
  at Symfony\Component\PropertyAccess\PropertyAccessor->writeProperty(array(object(BasketElement)), object(PropertyPath), '1')
     (vendor/symfony/property-access/PropertyAccessor.php:114)
  at Symfony\Component\PropertyAccess\PropertyAccessor->setValue(object(BasketElement), object(PropertyPath), '1')
     (vendor/symfony/form/Extension/Core/DataMapper/PropertyPathMapper.php:86)
  at Symfony\Component\Form\Extension\Core\DataMapper\PropertyPathMapper->mapFormsToData(object(RecursiveIteratorIterator), object(BasketElement))
     (vendor/symfony/form/Form.php:633)
  at Symfony\Component\Form\Form->submit(array(), true)
     (vendor/symfony/form/Extension/HttpFoundation/HttpFoundationRequestHandler.php:109)
  at Symfony\Component\Form\Extension\HttpFoundation\HttpFoundationRequestHandler->handleRequest(object(Form), object(Request))
     (vendor/symfony/form/Form.php:493)
  at Symfony\Component\Form\Form->handleRequest(object(Request))
     (vendor/sonata-project/ecommerce/src/BasketBundle/Controller/BasketController.php:133)
  at Sonata\BasketBundle\Controller\BasketController->addProductAction(object(Request))
     (vendor/symfony/http-kernel/HttpKernel.php:151)
  at Symfony\Component\HttpKernel\HttpKernel->handleRaw(object(Request), 1)
     (vendor/symfony/http-kernel/HttpKernel.php:68)
  at Symfony\Component\HttpKernel\HttpKernel->handle(object(Request), 1, true)
     (vendor/symfony/http-kernel/Kernel.php:198)
  at Symfony\Component\HttpKernel\Kernel->handle(object(Request))
     (public/index.php:25)
```

### PR DESCRIPTION
**Pull request by salamichel**
## Subject
Make the order process working on front  for symfony >4.1.

Closes #601 #610

## Changelog

```markdown

### Changed
- inject alias 'sonata.basket.factory' into basket controller
- change  'Free delivery' to 'free_address_required' in accordance with documentation https://sonata-project.org/bundles/ecommerce/master/doc/reference/bundles/delivery.html
```

### CODE REVIEW

**Comment by salamichel** [comment]
@greg0ire Hi, could you please review ? the travis issue is regarding xml lint i don't understand what's wrong. rgds

**Comment by greg0ire** [comment]
You can get some help from FlintCI. Click on `Details` on the FlintCI line, click the "Download raw diff" button, and apply it with `patch -p0`. I will give you more hints on the changes tab.

File: src/BasketBundle/Controller/BasketController.php [hunk 1]
```diff
@@ -35,6 +35,18 @@
...
 class BasketController extends Controller
 {
+    /* @var sonata.basket.factory */
+    private $basket_factory;
+    
+    /**
+     * 
+     * @param type $basket_factory
+     */
+    public function __construct($basket_factory)
```
Comment (greg0ire) [inline src/BasketBundle/Controller/BasketController.php]: There is a trailing whitespace. If you run `make cs-fix`, you will get rid of it.

File: src/BasketBundle/Controller/BasketController.php [hunk 2]
```diff
@@ -35,6 +35,18 @@
  */
 class BasketController extends Controller
 {
+    /* @var sonata.basket.factory */
```
Comment (greg0ire) [inline src/BasketBundle/Controller/BasketController.php]: `sonata.basket.factory` is not a valid type

File: src/BasketBundle/Controller/BasketController.php [hunk 3]
```diff
@@ -35,6 +35,18 @@
...
+    private $basket_factory;
```
Comment (greg0ire) [inline src/BasketBundle/Controller/BasketController.php]:
```suggestion
    private $basketFactory;
```

File: src/BasketBundle/Controller/BasketController.php [hunk 4]
```diff
@@ -35,6 +35,18 @@
...
+    
+    /**
+     * 
+     * @param type $basket_factory
+     */
```
Comment (greg0ire) [inline src/BasketBundle/Controller/BasketController.php]: You can remove this entirely

File: src/BasketBundle/Controller/BasketController.php [hunk 5]
```diff
@@ -35,6 +35,18 @@
...
+    public function __construct($basket_factory) 
+    {
+        $this->basket_factory = $basket_factory;
```
Comment (greg0ire) [inline src/BasketBundle/Controller/BasketController.php]:
```suggestion
        $this->basketFactory = $basketFactory;
```

File: src/BasketBundle/Controller/BasketController.php [hunk 6]
```diff
@@ -84,7 +96,7 @@ public function updateAction(Request $request)
             $basket->clean(); // clean the basket
 
             // update the basket
-            $this->get('sonata.basket.factory')->save($basket);
+            $this->basket_factory->save($basket);
```
Comment (greg0ire) [inline src/BasketBundle/Controller/BasketController.php]: Please change all the occurences to `basketFactory`

File: src/BasketBundle/Resources/config/basket.xml [hunk 7]
```diff
@@ -24,10 +24,14 @@
...
             <factory service="sonata.basket.loader" method="getBasket"/>
         </service>
-        <service id="sonata.basket.block.nb_items" class="Sonata\BasketBundle\Block\BasketBlockService">
+        <service id="sonata.basket.block.nb_items" class="Sonata\BasketBundle\Block\BasketBlockService" public="true">
             <tag name="sonata.block"/>
             <argument>sonata.basket.block.nb_items</argument>
             <argument type="service" id="templating"/>
-        </service>
+        </service>        
+        <service id="Sonata\BasketBundle\Controller\BasketController" >
```
Comment (greg0ire) [inline src/BasketBundle/Resources/config/basket.xml]: xmllint does not like this extra whitespace
```suggestion
        <service id="Sonata\BasketBundle\Controller\BasketController">
```

Comment (greg0ire) [reply src/BasketBundle/Resources/config/basket.xml]: similar issue below

**Comment by salamichel** [comment]
@greg0ire Hi, thank you for the explanation, it's very sensitive ;), it's should be OK now but travis won't start testing.

File: src/BasketBundle/Controller/BasketController.php [hunk 8]
```diff
@@ -35,6 +35,19 @@
...
 {
+    /**
+     * We inject alias 'sonata.basket.factory'.
+     */
+    private $basketFactory;
+
+    /**
+     * @param type $basketFactory
+     */
+    public function __construct($basketFactory)
```
Comment (core23) [inline src/BasketBundle/Controller/BasketController.php]: Please use a typehint here

File: src/BasketBundle/Controller/BasketController.php [hunk 9]
```diff
@@ -35,6 +35,19 @@
  */
 class BasketController extends Controller
 {
+    /**
+     * We inject alias 'sonata.basket.factory'.
+     */
+    private $basketFactory;
+
+    /**
+     * @param type $basketFactory
```
Comment (core23) [inline src/BasketBundle/Controller/BasketController.php]: `type` is not a valid class name or variable type

Comment (salamichel) [reply src/BasketBundle/Controller/BasketController.php]: I will remove entirely le hint, i can't use a valid typehint because we inject the alias 'sonata.basket.factory', who can be 'sonata.basket.session.factory' or 'sonata.basket.entity.factory', it's fine for you?

File: tests/Component/Basket/BasketElementTest.php [hunk 10]
```diff
@@ -276,9 +276,10 @@ public function testGettersSetters(): void
         $this->assertSame($product, $basketElement->getProduct());
 
         // Tests setProductId
+        $basketElement->setProductId('42');
+        $this->assertSame(42, $basketElement->getProductId());
```
Comment (OskarStark) [inline tests/Component/Basket/BasketElementTest.php]: Why twice? It’s the same in the next lines

File: src/Component/Delivery/FreeDelivery.php [hunk 11]
```diff
@@ -48,6 +48,6 @@ public function isAddressRequired()
 
     public function getName()
     {
-        return 'Free delivery';
+        return 'free_address_required';
```
Comment (OskarStark) [inline src/Component/Delivery/FreeDelivery.php]: Why this name change?

File: tests/Component/Basket/BasketElementTest.php (hunk 10 above)
Comment (salamichel) [reply tests/Component/Basket/BasketElementTest.php]: It's not the same test, here i want to test that if a string of quantity is set it must be return be work as well to an integer. I experienced issue from my side.

File: src/Component/Delivery/FreeDelivery.php (hunk 11 above)
Comment (salamichel) [reply src/Component/Delivery/FreeDelivery.php]: I followed the documentation https://sonata-project.org/bundles/ecommerce/master/doc/reference/bundles/delivery.html I was not able to "use an adresse" on the order delivery step

File: src/BasketBundle/Controller/BasketController.php (hunk 8 above)
Comment (salamichel) [reply src/BasketBundle/Controller/BasketController.php]: i've remove entirely as @greg0ire proposed

File: src/BasketBundle/Controller/BasketController.php [hunk 12]
```diff
@@ -35,6 +35,16 @@
  */
 class BasketController extends Controller
 {
+    /**
+     * We inject alias 'sonata.basket.factory'.
```
Comment (core23) [inline src/BasketBundle/Controller/BasketController.php]:
```suggestion
     * @var BasketFactoryInterface
```

File: src/BasketBundle/Controller/BasketController.php [hunk 13]
```diff
@@ -35,6 +35,16 @@
...
+     */
+    private $basketFactory;
+
+    public function __construct($basketFactory)
```
Comment (core23) [inline src/BasketBundle/Controller/BasketController.php]:
```suggestion
    public function __construct(BasketFactoryInterface $basketFactory)
```

File: src/BasketBundle/Controller/BasketController.php (hunk 8 above)
Comment (greg0ire) [reply src/BasketBundle/Controller/BasketController.php]: I proposed removing the phpdoc. Please use a typehint

Comment (salamichel) [reply src/BasketBundle/Controller/BasketController.php]: please confirm it's ok now ?

File: src/BasketBundle/Controller/BasketController.php [hunk 14]
```diff
@@ -35,6 +36,19 @@
  */
 class BasketController extends Controller
 {
+    /**
+     * @var BasketFactoryInterface
+     */
+    private $basketFactory;
+
+    /**
+     * @param BasketFactoryInterface $basketFactory A Sonata ecommerce basket interface
```
Comment (OskarStark) [inline src/BasketBundle/Controller/BasketController.php]: Can be removed

Comment (salamichel) [reply src/BasketBundle/Controller/BasketController.php]: Hi i'm confused, one time i need to use typehint one time i should remove. i really don't get the needed. i reproduced same as constructor found here https://github.com/sonata-project/ecommerce/blob/master/src/BasketBundle/Controller/Api/BasketController.php

this enhancement is mandatory when using sf 4.1, we are not able to use this king of code 
`$this->get('sonata.basket.factory')->save($basket);`

The alias is dynamically create in sonataBasketExtension.

Comment (pierredup) [reply src/BasketBundle/Controller/BasketController.php]: The typehint must stay, the docblock should be removed

Comment (salamichel) [reply src/BasketBundle/Controller/BasketController.php]: So i should remove  ` @var BasketFactoryInterface` and  `@param BasketFactoryInterface $basketFactory A Sonata ecommerce basket interface`  ?

Comment (OskarStark) [reply src/BasketBundle/Controller/BasketController.php]: Only the `@param.... `, because it does not add any value. its clear by the typehint

Comment (salamichel) [reply src/BasketBundle/Controller/BasketController.php]: Okay, done

File: src/BasketBundle/Controller/BasketController.php (hunk 8 above)
Comment (greg0ire) [reply src/BasketBundle/Controller/BasketController.php]: It is :)

File: src/BasketBundle/Resources/config/basket.xml [hunk 15]
```diff
@@ -24,10 +24,14 @@
         <service id="sonata.basket" class="Sonata\Component\Basket\Basket" public="true">
             <factory service="sonata.basket.loader" method="getBasket"/>
         </service>
-        <service id="sonata.basket.block.nb_items" class="Sonata\BasketBundle\Block\BasketBlockService">
+        <service id="sonata.basket.block.nb_items" class="Sonata\BasketBundle\Block\BasketBlockService" public="true">
```
Comment (greg0ire) [inline src/BasketBundle/Resources/config/basket.xml]: Why does this service need to be public? If there is a good reason, why not contribute it to the stable branch? It's not a BC break.

File: src/Component/Basket/BasketElement.php [hunk 16]
```diff
@@ -126,7 +126,7 @@ public function getProductId()
 
     public function setProductId($productId): void
```
Comment (greg0ire) [inline src/Component/Basket/BasketElement.php]: This is the `master` branch, you are allowed to make BC breaks and require and `int` here, by using a type declaration.

Comment (salamichel) [reply src/Component/Basket/BasketElement.php]: Done

File: src/BasketBundle/Resources/config/basket.xml (hunk 15 above)
Comment (salamichel) [reply src/BasketBundle/Resources/config/basket.xml]: no good reason, maybe wrong file updated when looked after the add basket issue

File: src/Component/Basket/BasketElementInterface.php [hunk 17]
```diff
@@ -64,10 +64,8 @@ public function getProductId();
     /**
      * Never call this method, use the setProduct instead. This method is only used
      * by the form framework.
-     *
-     * @param int $productId
      */
-    public function setProductId($productId);
+    public function setProductId(int $productId);
```
Comment (phansys) [inline src/Component/Basket/BasketElementInterface.php]: Shouldn't this method declare also `void` as return type?

**Comment by core23** [comment]
Thanks @salamichel
