### PR TITLE
Fix usage of not persisted addresses in BasketController

### LINKED ISSUE #444: Entities passed to the choice field must be managed
#### Sonata packages

```bash
$ composer show sonata-project/*
sonata-project/admin-bundle              3.18.2             The missing Symfony Admin Generator
sonata-project/block-bundle              3.3.2              Symfony SonataBlockBundle
sonata-project/cache                     1.0.7              Cache library
sonata-project/classification-bundle     3.3.0              Symfony SonataClassificationBundle
sonata-project/core-bundle               3.4.0              Symfony SonataCoreBundle
sonata-project/datagrid-bundle           2.2.1              Symfony SonataDatagridBundle
sonata-project/doctrine-extensions       1.0.2              Doctrine2 behavioral extensions
sonata-project/doctrine-orm-admin-bundle 3.1.4              Symfony Sonata / Integrate Doctrine ORM into the SonataAdminBundle
sonata-project/easy-extends-bundle       2.2.0              Symfony SonataEasyExtendsBundle
sonata-project/exporter                  1.7.1              Lightweight Exporter library
sonata-project/formatter-bundle          3.2.0              Symfony SonataFormatterBundle
sonata-project/intl-bundle               2.x-dev 90e304f    Symfony SonataIntlBundle
sonata-project/media-bundle              3.5.1              Symfony SonataMediaBundle
sonata-project/notification-bundle       3.1.0              Symfony SonataNotificationBundle
sonata-project/seo-bundle                2.x-dev 43c4437    Symfony SonataSeoBundle
sonata-project/user-bundle               dev-master 34a771f Symfony SonataUserBundle

```

#### Symfony packages

```bash
$ composer show symfony/*
symfony/assetic-bundle     v2.8.1  Integrates Assetic into Symfony2
symfony/monolog-bundle     v2.12.1 Symfony MonologBundle
symfony/phpunit-bridge     v3.2.8  Symfony PHPUnit Bridge
symfony/polyfill-intl-icu  v1.3.0  Symfony polyfill for intl's ICU-related data and classes
symfony/polyfill-mbstring  v1.3.0  Symfony polyfill for the Mbstring extension
symfony/polyfill-php56     v1.3.0  Symfony polyfill backporting some PHP 5.6+ features to lower PHP versions
symfony/polyfill-php70     v1.3.0  Symfony polyfill backporting some PHP 7.0+ features to lower PHP versions
symfony/polyfill-util      v1.3.0  Symfony utilities for portability of PHP codes
symfony/security-acl       v3.0.0  Symfony Security Component - ACL (Access Control List)
symfony/swiftmailer-bundle v2.5.4  Symfony SwiftmailerBundle
symfony/symfony            v3.2.8  The Symfony PHP framework

```

#### PHP version

```bash
$ php -v
PHP 7.0.15 (cli) (built: Jan 17 2017 13:58:38) ( ZTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies

```

## Subject
Looks like having a [mapped:false](https://github.com/sonata-project/ecommerce/blob/2.x/src/BasketBundle/Form/AddressType.php#L85) field in a form can't be an entityField.

## Steps to reproduce
Add a product to basket, "next step", insert delivery address and go to next step.
go to a random page
return to basket and click "next step" the procedure, the error will occur 

## Actual results
got the following error:
`Entities passed to the choice field must be managed. Maybe persist them in the entity manager?
`

### PR DESCRIPTION
**Pull request by ZRazor**
I am targeting this branch, because it's a bug fix.

Closes #444 

## Changelog

```markdown
### Fixed
- Fixed usage of not persisted addresses when the customer is taken from a session.
```

## Subject
I suppose this is not the best way to do it, but other ways involve reworking the whole structure of order process or BC break.

We definitely need to change the order process in the next major.

### CODE REVIEW

File: src/BasketBundle/Controller/BasketController.php [hunk 1]
```diff
@@ -360,6 +360,14 @@ public function deliveryAddressStepAction()
 
         $addresses = $customer->getAddressesByType(AddressInterface::TYPE_DELIVERY);
 
+        // Remove not persisted in DB addresses
```
Comment (OskarStark) [inline src/BasketBundle/Controller/BasketController.php]: the sentence sounds strange

Comment (ZRazor) [inline src/BasketBundle/Controller/BasketController.php]: I'll remove it, there is no actual need in this comment.

File: src/BasketBundle/Controller/BasketController.php [hunk 2]
```diff
@@ -360,6 +360,13 @@ public function deliveryAddressStepAction()
 
         $addresses = $customer->getAddressesByType(AddressInterface::TYPE_DELIVERY);
 
+        $em = $this->container->get('sonata.address.manager')->getEntityManager();
+        foreach ($addresses as $key => $address) {
+            if (!$em->contains($address)) {
+                unset($addresses[$key]);
+            }
+        }
```
Comment (greg0ire) [inline src/BasketBundle/Controller/BasketController.php]: Please add a comment explaining when this is useful.

**Comment by greg0ire** [comment]
Can you please sum up briefly #444 in your commit message body?
Please format your commit message according to our rules : 

- The commit message subject must be less than 50 characters and tell us *what* you did.
- The commit message body should tell us *why* you did it. It is optional but highly recommended.

More details in CONTRIBUTING.md

**Comment by ZRazor** [comment]
@greg0ire, is it better now? I tried hard )

**Comment by greg0ire** [comment]
The body is way better!!! The subject could be improved by replacing the reference to the BasketController to something more abstract, like "Prevent unmanaged addresses usage in choice field" (exactly 50 chars :P )

**Comment by jordisala1991** [comment]
> We definitely need to change the order process in the next major.

Do we need to add a comment on that code to show this? Just to remember for the next major?

**Comment by ZRazor** [comment]
@jordisala1991, It was not just about this piece of code, but about the whole order process (there is too much logic in BasketController), so I don't think that it will be any useful here.

**Comment by greg0ire** [comment]
Thanks @ZRazor !
